---
  - name: Stop RabbitMQ app in the extra task nodes
    command: /sbin/rabbitmqctl stop_app
    
  - name: Join extra task nodes under RabbitMQ cluster
    command: /sbin/rabbitmqctl join_cluster rabbit@{{ ansible_hostname }}
    
  - name: Start RabbitMQ app in the extra task nodes
    command: /sbin/rabbitmqctl start_app
    