---
  - name: Stop RabbitMQ app in the extra web nodes
    command: /sbin/rabbitmqctl stop_app
    
  - name: Join extra web nodes under RabbitMQ cluster
    command: /sbin/rabbitmqctl join_cluster rabbit@ansible_host
    
  - name: Start RabbitMQ app in the extra web nodes
    command: /sbin/rabbitmqctl start_app
    