---
- hosts: "{{ variable_host | default('awx_instance_group_*') }}"
  become: yes
  become_method: sudo

  vars:
    ### AWX Default Settings
    awx_unique_secret_key: awxsecret
    awx_admin_default_pass: password

    ### Postgre DB details
    pg_db_host: "Database_Node_IP"
    pg_db_pass: "awxpass"
    pg_db_port: "5432"
    pg_db_user: "awx"
    pg_db_name: "awx"

    ### RabbitMQ default settings
    rabbitmq_cookie: "cookiemonster"
    rabbitmq_username: "awx"
    rabbitmq_password: "password"

  roles:
    - { role: rabbitmq_cluster, when: ansible_os_family == "CentOS" and ansible_distribution_major_version == "7" }
    - { role: awx_ha, when: ansible_os_family == "CentOS" and ansible_distribution_major_version == "7" }
