---  
  - name: Start Firewalld
    systemd:
      name: firewalld.service
      state: started
      enabled: yes

  - name: start rabbitmq server
    systemd:
      name: rabbitmq-server.service
      state: started
      enabled: yes

  - name: restart rabbitmq server
    systemd:
      name: rabbitmq-server.service
      state: restarted

  - name: reload firewalld 
    command: firewall-cmd --reload
